# Site settings
title: Energian hintavertailu
email: joneskoo+energia@derbian.fi
description: > # this means to ignore newlines until "baseurl:"
  Vertaile eri sähkösopimusten todellisia kustannuksia todelisten
  tuntikulutustietojesi perusteella!
baseurl: "/energiavertailu" # the subpath of your site, e.g. /blog/
url: "https://joneskoo.github.io" # the base hostname & protocol for your site
twitter_username: joneskoo_yx
#github_username:  joneskoo

# Build settings
markdown: kramdown
